### ISSUE TITLE
Press a keybind to activate

### ISSUE THREAD

**Issue by jmshgs** [danielsaidi/QuickSearch#2]
Could you add a feature where instead of the search bar always being focused, it focuses when a keyboard combination is pressed? (I'd like to use cmd + F).

Thanks!

**Comment by danielsaidi** [comment]
Hi @jxhug 

Sure, but cmd+F should work by default.

**Comment by jmshgs** [comment]
With `.searchable`? Unfortunately it doesn't. It does in Apple apps because they have a private way, but in other apps you cannot. Thanks!

**Comment by danielsaidi** [comment]
I ran into a problem with this. I added a custom key binding that worked and detected the cmd+f, but...since the solution is based on a focusable view, that view losing focus means that it's no longer able to detect the keyboard shortcut.

**Comment by danielsaidi** [comment]
I however added a custom focused binding to make it possible to control the focus of that view.
